### ISSUE TITLE
Adding timestamp field by combine tracker_month and tracker_year to YYYY-MM-01

### ISSUE THREAD

**Issue by lboel** [CorrelAidSwitzerland/a4d#100]
This could help in various cases in Looker but also allow more general time frames in BQ (like eg. selecting all data before May 2021 and after March 2020).

**Comment by pmayd** [comment]
Ideally we dont even need the day here, have to check

**Comment by lboel** [comment]
Looker supports Year Month (https://support.google.com/looker-studio/answer/6401549?sjid=12041770987455184107-EU#zippy=%2Cin-this-article)

but I would just use "Date" format, for compatibility reason with SPSS. Although unix timestamp is the best way in terms of interoperability between all systems (R,BQ,Looker/Sheets), I remember having a hard time with SPSS (Syntax needed to parse, format back to date etc).

**Comment by pmayd** [comment]
Yeah it is more about Big Query because that is where the data is ingested so we have to check there. But I see no problem with using a normal date one should be able to easily ask Looker to omit the day

**Comment by pmayd** [comment]
I have implemented a solution and created a PR.
