### ISSUE TITLE
Adding clinic_data_static to the reference_data (Matching Code with Clinic Names/Province/Yearly_quota

### ISSUE THREAD

**Issue by lboel** [CorrelAidSwitzerland/a4d#108]
At the moment there is no reference data that matches clinic codes to their names and other static clinic dates. 

For consistency reason the quota values are added as well "quota_22". This value seems to be a targeted manual value that changes from year to year. 

We don't have a clear workflow that allows this kind of data to be dynamically edited, so the first approach is to add this to the repo in the reference data and then just ingest it in script 3 with the other tables.

**Comment by lboel** [comment]
I am not totally sure but if we want some kind of static data ingesting in the pipeline (to avoid manually uploading this csv). the #109 makes a straight forward approach. 

I am not sure about the ingesting code in the PR Branch, but it seems the easiest way to avoid any schema files and the csv stays easily adaptable (although it`s in the repo now, but this data won`t probably change often over time (only if new clinics are added)).

**Comment by pmayd** [comment]
Why do we need this at all? At the moment it is not used in any script so I guess you added it so we have a pipeline for creating the table? Creating the whole table in BQ/SQL would have the discussed advantage that a4d can change it at any time but I guess it is ok in reference data, too

**Comment by lboel** [comment]
My goal would be to have anything that is needed to set the system up and some time in the repo.
So having the current needed queries for views in the Repo as well. These are not ingested by the script but are there for documentation reasons. 

So the idea is, that a completely new team, can set up everything in a new BQ instance. As soon as there is a productive usage, we might end up having the reference_data in google_sheets. So it could be directly edited and automatically mirrored to BQ for further processing. 

But for now, the main idea behind this issue is, just to ensure that we have some kind of universal checkpoint and the end of the years. So I continue to add the documentation of the current view queries as well and some short description of the current looker reports). 

The Release version at the end of the year would than contain anything to recreate our current status.
