### ISSUE TITLE
Possible misidentification of clinic name (example of product data)

### ISSUE THREAD

**Issue by tvolegtv** [CorrelAidSwitzerland/a4d#127]
The following situation is possible in product data - incorrect definition of Clinic Name in case the number of patients from another clinic is greater than the number of patients from the current clinic: 

![Image](https://github.com/CorrelAidSwitzerland/a4d/assets/85793780/25f930ec-e6b8-4737-aa97-d304c6bbb27b)

Possible solution:
1. Synchronizing the clinic name for product data with the patient_data_monthly table for each file_name
2. Change the rule for extracting clinic name from patient ID - i.e. ignore the Clinic Name in positions 4-5 if the patient ID includes 2 clinic names.

**Comment by pmayd** [comment]
I see, so this happens because you have your own logic extracting this? Yes please let's take this information from the patient data because there we have this information already, but honestly I take it from patient id, too, so what are you doing? Is it a problem when we take it from patient id?

**Comment by tvolegtv** [comment]
As I see, we have the same logic for patients and products. 

Patient ID:
2 characters before the 1st _ : country code 
2 characters after the 1st _ : clinic code.
For the tracker file, the clinic name and country name are determined by the most frequent value.

In the example I see now (2022_Preah Kossamak Hospital A4D Tracker, the picture above) - the current clinic name is encoded in the last 2 characters in the patient id - KH_KB002_**PK** (PK in this case).
The 2 characters after the 1st "_" stands for the original clinic - not the current clinic.

So if we have a tracker file with a situation where the largest number of patients are not from the current clinic, the clinic name will be defined incorrectly. 
It seems that the same situation can happen with patient data. What do you think? 

Because we define clinic name after fix_id(id) for patients data too - run_script_2_clean_data.R:
```
    # add clinic and country code after having fixed all issues with patient id
    cc_codes <- extract_country_clinic_code(df_patient)
    df_patient["clinic_code"] <- cc_codes$clinic_code
    df_patient["country_code"] <- cc_codes$country_code
```

**Comment by pmayd** [comment]
Thanks oleg, now it is clear. But then the problem is that this is against the rules or better against the agreement we had with Tyla. The rule that she gave us was that patient id remains always the same and if the patient moves to a new clinic, the new clinic is appended...

It is not hard to change the logic, I already have a fix function for patient id that could easily check if the id is longer and take the last two letters as clinic code but we have to make sure that this is always the right approach

**Comment by tvolegtv** [comment]
You're right! The current product data has both rules. I think they are in the patient data as well. 
I will prepare an example for Tyla (based on the product data) and send it after this holiday.
There may be more files with incorrect rules in the patient data. But I think the first example based on product data should be enough.
I see that in this case only manual correction is possible to make one rule for all files..... 

```
1. Correct (against the agreement we had with Tyla):
2021_Chiang Mai Maharaj Nakorn Hospital A4D Tracker
2021_Sunprasitthiprasong Hospital A4D Tracker
2022_Chiang Mai Maharaj Nakorn A4D Tracker

2. Incorrect (the current clinic name is encoded in the last 2 characters in the patient id - KH_KB002_PK - PK in this case):
2021_Khon Kaen Hospital A4D Tracker
2021_Preah Kossamak Hospital A4D Tracker
2022_Khon Kaen Hospital A4D Tracker
2022_Mahosot Hosptial A4D Tracker_DC
2022_Preah Kossamak Hospital A4D Tracker
```

**Comment by pmayd** [comment]
Solved by switching to clinic id instead of clinic code, which is unique
