### ISSUE TITLE
Solve mutate() `insulin_dosage` error in `cleaning_a4d_tracker()` function when running `10_Run..R` with >2018 real data

### ISSUE THREAD

**Issue by mischanvp** [CorrelAidSwitzerland/a4d#19]
Adapt script to account for missing columns such as insulin_dosage.

**Comment by pmayd** [comment]
@mischanvp and @tvolegtv is this still accurate? Is this issue still a problem? Or can we close it?

**Comment by mischanvp** [comment]
I think you guys solved it? @YannLadner . This was an error in the patient data at the very start.

**Comment by pmayd** [comment]
Probably it's just your issue so I wanted to let you close it :)
