### ISSUE TITLE
writing a test suite

### ISSUE THREAD

**Issue by pmayd** [CorrelAidSwitzerland/a4d#22]

**Comment by YannLadner** [comment]
If the `a4d` package is loaded, `devtools::test_coverage()` fails for me because the package is in use.
And `.Rprofile` will automatically load `a4d`.

In that case, I first ran `detach("package:a4d")` and it worked again.
Not sure how you dealt with this issue.

**Comment by pmayd** [comment]
What do you mean, I have no problems with the current setup? We don't load our package, we use load _all?

**Comment by YannLadner** [comment]
Yes, I mean `a4d` is automatically loaded (using `load_all()`) whenever we open the project in Rstudio.

Because of that part in `.Rprofile`:
```r
if (interactive()) {
    require("devtools", quietly = TRUE)
    # automatically attaches usethis
    devtools::load_all()
}
```

So when I then try to run `devtools::test_coverage()`, I get an error:

```r
Warning: package ‘a4d’ is in use and will not be installed
Error in file(con, "r") : cannot open the connection
In addition: Warning message:
In file(con, "r") :
  cannot open file 'C:/Users/Yann/AppData/Local/Temp/RtmpgnTMxe/R_LIBS406035e057d2/a4d/R/a4d': No such file or directory
```

**Comment by pmayd** [comment]
Ok I will test it later but I don't understand because usually that is the first command I run when opening RStudio because we need access to the functions hm

**Comment by pmayd** [comment]
Ok strange I just run the command after openen RStudio and as expected everything works just fine:
![image](https://user-images.githubusercontent.com/9614291/235737718-bae2c8ec-c3c4-42d1-9260-a073532bf797.png)
