### ISSUE TITLE
Find a way to pseudoanonymize/scramble real data for RMarkdown and similar use cases

### ISSUE THREAD

**Issue by pmayd** [CorrelAidSwitzerland/a4d#45]
So after @YannLadner introduction to RMarkdown we noted that this would be most helpful for data analysts and data scientists sharing their work and findings. However, if we do this, especially as part of the repository and uploading it to GitHub, we have to make sure that no real data is stored within the RMarkdown or Markdown files. 

So my idea is that we can use some package that will scramble or pseudoanonymize the data (for example a data frame) so we can use it inside the RMarkdown file to share our findings with the others.

**Comment by YannLadner** [comment]
Prepared a demo, but will need to think about which exact variables (columns) need to be scrambled).

Amongst all the different trackers, we will definitely need to scramble:
- Patient ID
- Patient name
- Date of birth
- Age

Not sure about other variables that might make it easy to find out who it is, such as Education, Hospital Name, _etc._

Maybe also, if the scrambling algorithms are good enough. Not an expert in security.

**Comment by YannLadner** [comment]
Quick demo file can be seen here: https://github.com/CorrelAidSwitzerland/a4d/blob/ea9d0cb4ba4c0705e537593e0efaa5f0619abe62/Scramble_demo.md
It just uses an example dataset.
One can play around with `Scramble_demo.Rmd` on the branch [45-scramble-sensitive-data](https://github.com/CorrelAidSwitzerland/a4d/tree/45-scramble-sensitive-data) to test it using our data.
At the bottom of `Scramble_demo.Rmd`, I used the `.RData` files I got from [pmayd-run-main-script-as-loop](https://github.com/CorrelAidSwitzerland/a4d/tree/feature/pmayd-run-main-script-as-loop).

**Comment by YannLadner** [comment]
Has been solved using the script `get_mapping_table.R`
However, scrambling will most likely not be used anymore, since we will move to a virtual machine.
