### ISSUE TITLE
Write extraction/anonymization script to run locally on A4D computer (script 1)

### ISSUE THREAD

**Issue by YannLadner** [CorrelAidSwitzerland/a4d#58]
Most likely, it will be easier to just write a new script using parts of our current codebase.
~~Would make sense to extract tracker data with all columns being of character type. Otherwise, type coercion might lead to loss of information.~~ not a problem.

Current questions:

- Do trackers within a year differ from each other?
  - Yes, 2017 trackers do not have the sheet "Patient List" - sensitive data is integrated into monthly sheets.

**Comment by YannLadner** [comment]
Current progress can be found on the following branch: https://github.com/CorrelAidSwitzerland/a4d/tree/fix/run-2022-patient-dummy-data
The following script can be run: `Run_extraction_script_1_patients.R`

Script still needs to implement the following:
- Combining the data within the monthly sheets with the "Patient List" sheet (only for 2022 data - 2017 already contains this info within the monthly sheets).
- 2022_LWC.xlsx has different units for updated FBG - mmol/L, as opposed to files.
- Removing all the sensitive columns (I just set them to NA ).
- Looping over all files.

**Comment by pmayd** [comment]
for the last point we have to ask Tyla how she is storing the trackers right now and adjust our script to her folder structure

**Comment by YannLadner** [comment]
Yeah, or just tell her to add all of them to a folder and then we just choose the folder interactively and it will run over all the files.

**Comment by pmayd** [comment]
yeah sure but we should stick to her process as much as possible

**Comment by pmayd** [comment]
Doesn't make sense for her to copy for example 100 files from 40 subfolders into one folder ;)

**Comment by pmayd** [comment]
I would rename the branch to something else so if you continue your work you have to checkout the other branch, will have a look now

**Comment by pmayd** [comment]
New branch is called feat/script-1-remove-sensitive-data

**Comment by YannLadner** [comment]
> Doesn't make sense for her to copy for example 100 files from 40 subfolders into one folder ;)

Oh yeah, makes sense!

> New branch is called feat/script-1-remove-sensitive-data

Sounds good, checked out.

**Comment by YannLadner** [comment]
Should we rename the branch so it is clear that is only for the patient side. Or will the others for the product data also work on this one?

**Comment by YannLadner** [comment]
Never done pair programming before. Do you want to do it now?

**Comment by YannLadner** [comment]
Ah ok, yeah sure.

See you this evening then!

**Comment by YannLadner** [comment]
Reason why there is the following warning:
```r
Warning message:
In dplyr::left_join(df_raw, patient_list %>% dplyr::select(-c(baseline_fbg,  :
  Detected an unexpected many-to-many relationship between `x` and
`y`.
ℹ Row 13 of `x` matches multiple rows in `y`.
ℹ Row 1 of `y` matches multiple rows in `x`.
ℹ If a many-to-many relationship is expected, set `relationship =
  "many-to-many"` to silence this warning.
``` 
In the monthly sheets of `2022_KKN.xlsx`, there are entries in row 13 (also formulas), which should be empty. If all the entries are emptied, this warning does not appear anymore.

**Comment by YannLadner** [comment]
For `2018_PNG.xlsx`, there is a warning when parsing the numbers within the monthly sheet names, because they do not exist for this tracker. 
This warning will stop the extraction of the patient data.

We can still extract the data by just removing the warning part of the `tryCatch()`:

```r
tryCatch(
            process_tracker_file(paths, tracker_file, synonyms),
            error = function(e) {
                logError("Could not process ", tracker_file, ". Error = ", e, ".")
            },
            warning = function(w) {
                logWarn(
                    "Could not process ",
                    tracker_file,
                    ". Warning = ",
                    w,
                    "."
                )
            }
        )
```

Or we add `suppressWarnings()` to the `parse_number()`.
But there a problem with the product data, since they get the product_year from parsing the monthly sheets.
For the patient data, the year can also be extracted by getting a 4 digit number.

**Comment by pmayd** [comment]
Where is this warning comming from? I mean where in the code is this happening? THe product data should use the same logic as we do: when we cannot extract the year from the sheet we take the file name.

**Comment by YannLadner** [comment]
The year is extracted first from the month_list and if it is NA from the tracker file name.
For the product data, this was not yet the case. But I just pushed the changes to https://github.com/CorrelAidSwitzerland/a4d/tree/feat/script-1-remove-sensitive-data.
Now, the code does not stop anymore when there are warnings during the `parse_number()` and the product code will extract the year from the file name.
