### ISSUE TITLE
Finish product data

### ISSUE THREAD

**Issue by pmayd** [CorrelAidSwitzerland/a4d#65]
There are 2 issues at the moment: 

1. Non-processed dates in product_entry_date. For example, in 2021_SWK: 24-N0v-202, 2-N0v-2021. Currently, these kind of dates are ignored.
2. Fixed Schema: the CSV file generated by Script3 should include all product fields and these fields should be in fixed positions. (i.e. product_balance position should be stable, now it could be column 3 or 12, etc.) 
3. product_country and product_hospital - Get from Patient ID

**Comment by pmayd** [comment]
@tvolegtv can you please fill out this issue (edit description) and list all open tasks as we discussed in the last meeting? We now have three new team members so at least 1-2 should be able to help you here asap! @chroschie and @KonradUdoHannes

**Comment by tvolegtv** [comment]
There are 2 issues at the moment, all others from the last meeting's list we have already fixed with @mischanvp

**Comment by pmayd** [comment]
For 1. please just log it as a warning

**Comment by tvolegtv** [comment]
Sure, it works this way already – it is a function non_processed_dates in read_product_data.R. It puts non-processed dates on the log.
