### ISSUE TITLE
Proper error report

### ISSUE THREAD

**Issue by pmayd** [CorrelAidSwitzerland/a4d#67]
Right now our error report is a Jupyter notebook I wrote to parse the log messages.

Ideally, we can either improve this notebook or create a proper error report so that we can just start a script and a detailed error report is generated.

The error report should report standard statistics about the data ingestion process like how many files were processed, how many successfully, how many errors overall, how many warnings (avoid duplicates), list all files with errors or warnings, kind of warnings per file etc. 

This is linked to #66  but not dependent on it as the logic of the report can be implemented even if the log messages are improved further. However, of course, if we parse log messages it is important to know their structure so ideally whoever works on this issue is also doing #66.

**Comment by lboel** [comment]
this will now be solved by a shiny-app that soon will be merged here in the repo

**Comment by lboel** [comment]
Added a Working Branch for the Shiny App.
