### ISSUE TITLE
Fix problems with bq cli tool when ingesting data

### ISSUE THREAD

**Issue by pmayd** [CorrelAidSwitzerland/a4d#70]
When running our current ingest script: 
```bash
bq load --source_format CSV --clustering_fields id,tracker_year,tracker_month --encoding UTF-16LE --project_id=a4d-315220 --skip_leading_rows 1 --max_bad_records 100 a4d_ds_tracker.patient_data "gs://a4d-315220-clean-data/patient_data/*.csv" scripts/gcp/schema.json
```

we get the following error (as example, this occurs for several files):

`[gs://a4d-315220-clean-data/patient_data/2022_Surat Thani A4D Tracker_patient_cleaned.csv] Error while reading data, error message: CSV table references column position 45, but line starting at position:2870 contains only 17 columns. File: gs://a4d-315220-clean-data/patient_data/2022_Surat Thani A4D Tracker_patient_cleaned.csv`

I don't really understand why this happens but it seems that some rows do not have the correct number of columns, maybe this is related to what @tasosbada said about new line characters in the strings. So we have to fix this

**Comment by tasosbada** [comment]
The problem is due to observations that have new lines in the string, we can easily solve the problem using the option`--allow_quoted_newlines=true`

**Comment by tasosbada** [comment]
In addition to remove any existing data we have to add  the flag `--replace=true` this replaces the all the existing data and schema, otherwise it appends all and we will have duplicates.

**Comment by pmayd** [comment]
This is my current command with no errors at all!
```bash
bq load --source_format CSV --encoding UTF-16LE --project_id=a4d-315220 --skip_leading_rows 1 --max_bad_records 100 --allow_quoted_newlines=true --replace=true a4d_ds_tracker.patient_data "gs://a4d-315220-clean-data/patient_data/*.csv" scripts/gcp/schema_patient_data.json
```
