### ISSUE TITLE
Provide longitudinal data for patients with regard to hba1c

### ISSUE THREAD

**Issue by pmayd** [CorrelAidSwitzerland/a4d#71]
After my discussion with Tyla today (2023-09-26) it became clear that one very important kind of data is longitudinal patient data. This kind of data is given to the medical experts to prepare the publications.

Currently, the data is stored in long format with regard to `id`, `tracker_year` and `tracker_month` meaning that each patient has a new row for each new measurement. 

However, what A4D needs is the wide format, so one patient with all the measurements as columns. This is more than just translating the data because as of now we have repeated measurements. This means that the old measurement is repeated each month until there is a new measurement. There is no easy way to recognize a new measurement, as the column "clinic_visit" was only introduced in 2022. So the only way to detect a new measurement is by comparing it with the previous month and see if the value has changed.

So I guess the best approach here is to write a new script for the 3rd phase and prepare a new data set that we will upload in a new table for longitudinal data. All the basic fields can be left out as this is part of the static patient data table and can be joined in. But we have to process all the dynamic patient data, calculate a diff for the hba1c column and only keep the rows where the value changes (or replace repeating values with NA).

We could use the column `last_clinic_visit` but here again it might happen that the clinic forgot to update the field. So we have to check if this is reliable otherwise we have to do it in the way decribed above.

So output is something like this:
- new script that prepares the data as needed for hba1c
- new table in BQ that makes the data available
- new logs

**Comment by tasosbada** [comment]
It seems to work.

Table or view with creation using only the rows that have changes, while it sorts the data based on time and cluster them using the patient Id.

`create or replace table `ds_trackers.tb_patient_changes ` as(with tb_temp_patient_changes as (
select abs(hba1c_updated - LEAD(hba1c_updated) over ( partition by id order by hba1c_updated_date )) as diff_hba1c, * from `ds_trackers.tb_patient_v1`
)
select * from tb_temp_patient_changes
where diff_hba1c > 0.000001
order by id, hba1c_updated_date)` 




![Image](https://github.com/CorrelAidSwitzerland/a4d/assets/15861245/84451daf-5551-4ed6-8dc5-5731c9299330)

**Comment by pmayd** [comment]
Wow great work it seems I know too little SQL...I was not aware that this is possible. I have to study your query a little longer to understand it but cool that you tried to solve it as query! But I fear we need it transposed so I am not sure if SQL will work here...and if we transpose the schema will change because with each month we get a new column...

**Comment by pmayd** [comment]
Wow great work it seems I know too little SQL...I was not aware that this is possible. I have to study your query a little longer to understand it but cool that you tried to solve it as query! But I fear we need it transposed so I am not sure if SQL will work here...and if we transpose the schema will change because with each month we get a new column...

**Comment by pmayd** [comment]
So we would need to make the result in long Format with a single patient row and all updates as columns and each patient can have different columns...but maybe we don't have to recreate the exact same format maybe it is just fine to have it this way because it is much easier for us and the medical experts can change the format how the like but the information is basically there...

**Comment by pmayd** [comment]
And I have one problem with your code: does it not compare any value against the last value? I think this will miss something in very special cases: think about the sequence A B C D B D. Your code will compare every value against the last value D for this group, which means we keep A and B but not the first D because it is identical, right?

**Comment by lboel** [comment]
I think this should be done in R to avoid another sql code-base. 

So the issue more relates to a general long to wide format conversion of all dynamic numeric data fields, or not?

So the best approach would be to use somekind of data point counter var and the date and measurement value as the wide data columns:

Thinking of: 

| ID | 1_date | 1_hba1c | 1_hba1c_diffprev | 2_date | 2_hba1c | 2_hba1c_diffprev | ... |

(diffprev would be optional here, because it is theoretically calculatable by the other two columns.)


Could be adaptable to any changing variable. Probably there are issues with identical dates but changing values (?), or other edge cases. But this structure would allow us to essential add all changing vars to one wide table that can be further processed and e.g. for the plots be reformated to long easily.

**Comment by pmayd** [comment]
I am not sure I understand what You are trying to say here? At the moment it is only about hba1c so we have no other dynamic variables like weight. We only have static variables so the idea is to create one table/df with only the longitudinal data which basically means the patient id and the monthly values and then join this with the static patient data.

So of course if we write this logic we can easily do this for all variables so later on A4D can simply select which variable they want to see because we have prepared everything. But I don't think we need this counter variable you are talking about. We basically just need to calculate the difference of the target column like Anastasios did and then only keep rows where the difference is unequal zero. And for each patient this will be different dates of course.

We just have to check how big query handles a dynamic schema because in this case we don't know the number of columns in advance...but let's first concentrate on the r code

**Comment by lboel** [comment]
Okay. I was just thinking that age or weight have different values overtime as well, so I wanted to propose a universal approach to this. So the idea would be that a person age over time so age wouldnt be necessarily a "static" var. 
The column counter variable would be something like "measurement counter" by keeping the exact values ( of course only keeping changing values) we probably end up with an easier way of filtering in Looker and error handling.

Having a counter var would just need to define a maximum of possible measures per patient. So something like 100 might be sufficient (or much less). Filtering completly empty columns on the looker end would be very easy in SQL then.

**Comment by tasosbada** [comment]
> And I have one problem with your code: does it not compare any value against the last value? I think this will miss something in very special cases: think about the sequence A B C D B D. Your code will compare every value against the last value D for this group, which means we keep A and B but not the first D because it is identical, right?
> 
> And I think there is another problem with the last value, if I understand your code correctly you sort ascending by date so Lead returns the last date? But that means that this value will not be part of the result as the last value is identical to Lead value. But we need both the start and end value included, if they are different from the one before

The snippet was basically a first attempt to investigate whether we can implemented it directly in the bq. You are right that we lose the last, but can find a way to go around this problem. Probably using the LAG instead of LEAD and try to merge the first ever visit of each patient.

Related to the code, in the beginning we partition and group by, this means that we generate a column with the difference of sequence rows. In this case, the example-column 1.A 2.B 3.C 4.D 5.B 6.C all of the row are dynamic, since 1.A-B 2. B-C 3. C-D 4.D-B 5. B-C 6. null. So expect of the problem that we lose the last row all the other rows are kept.

**Comment by tasosbada** [comment]
I have change a changed a little bit the query for the table generation.

`create or replace table `a4d_ds_tracker.tb_patient_changes` as(with tb_temp_patient_changes as (
select abs(hba1c_updated - LAG(hba1c_updated) over ( partition by id order by hba1c_updated_date )) as diff_hba1c, * from `a4d_ds_tracker.patient_data_v2`
)
select * from tb_temp_patient_changes
where diff_hba1c > 0.000001 or diff_hba1c is null
order by id, hba1c_updated_date)
`
Now we select not only the row with changes but the first row for each patient which always hav  difference equals to null.
I think that we are not losing any row now.

One possible edge case that I could think is the case where the patient is visiting but the measured value is exactly the same.

**Comment by pmayd** [comment]
@lboel could you have a look at my PR?
