### ISSUE TITLE
Make sure product data can be linked with patient data

### ISSUE THREAD

**Issue by pmayd** [CorrelAidSwitzerland/a4d#80]
Right now we are handling product and patient data completely isolated from each other and that is deliberately so. However, we should make sure that product data can be actually linked to patient data. This is only possible by the patient name that appears in the "Released To" column of product data.

So the idea is to do a merge/join of the two final data sets (product data and patient static data) and see if there are any entries in product data that do not have a match with patient data. If so, we should tell Tyla about it/generate a report and see if the files can be fixed manually.

**Comment by pmayd** [comment]
@tvolegtv I would see you here in the lead for this issue so if someone wants to do this please connect with Oleg

**Comment by pmayd** [comment]
Depends on data being available in the database

**Comment by tvolegtv** [comment]
I added the function 'link_product_patient' in Script 3 –
This function links a product csv file (product_data.csv) with a patient csv file (patient_data_monthly.csv). It reads the csv files, merges them based on 'file_name' and patient 'id', finds the ids that are in the product data but not in the patient data, creates a summary of these ids, and logs the results into link_product_patient_data.log
