### ISSUE TITLE
Product/inventory report

### ISSUE THREAD

**Issue by pmayd** [CorrelAidSwitzerland/a4d#87]
This should be based on the Excel file Tyla send us: `CSP Impact_Numbers.xlsx`

There is a sheet for each product so we can concentrate for now on the overall structure and one product.

Here is more information about it from Tyla:

Hi Michael

Yes, apologies for not sending it sooner - here is the report we use to estimate the total supplies issued per clinic.
It's estimated using formulas based on patient numbers. I suspect it is quite over estimated as I believe the patients tend to use fewer supplies than they should, for example if they can't come to the clinic regularly (we don't encourage this but unfortunately it is the reality).

In any case, it would be great to see something similar based on actual supplies issued.
We will need to group the different stock items together - for example, if we have different products which are all insulin cartridges 3ml of the same type of insulin we can put them under the same total (if that makes sense).

Many thanks!

Tyla

**Comment by pmayd** [comment]
@tvolegtv I think we need to look at her request to group different stock items together, I think you know what she means, I don't but basically I think there are different product types all falling for example under insulin cartridges. Do we have such a grouping of products?

**Comment by tvolegtv** [comment]
@pmayd   We have a list of 66 products. This list is in master_tracker_variables.xlsx (Stock_Summary) I use it to report unknown products in script2 (read_product_data.R\report_unknown_products).
The original file from Tyla has 6 categories for these products:
1. TEST STRIPS
2. LANCETS
3. INSULIN
4. PENS, NEEDLES & SYRINGES
5. GLUCOMETERS
6. OTHER

We have two options:
- We can add more columns with different categories in scrip3. But this requires a 'cleaned' list of products and categories before running script3. It could mean that script3 is not fully suitable for the final product grouping.
- Or we can use Looker to create different categories (including the ones above) when we do analysis. But I'm not sure if Looker Studio can do that like, for example, Power BI can.

**Comment by pmayd** [comment]
Yes I would always prefer adding new columns in our scripts as the data should be independent of the database or BI tool, otherwise you get real problems later on if you have logic in three different  places (R, SQL, Looker).

So the right place for new columns is script 2 where we also introduce new columns for patient data. So I suggest we clean the product names and afterwards add the category as new column

**Comment by pmayd** [comment]
@tvolegtv what about this story?

**Comment by tvolegtv** [comment]
it was done in script 2
