### ISSUE TITLE
Create a view with all patient data

### ISSUE THREAD

**Issue by pmayd** [CorrelAidSwitzerland/a4d#89]

**Comment by tasosbada** [comment]
@pmayd could give more details about what do you mean with all patient data, is it a merge of two tables? You already generated a new dataset, is it already done?

**Comment by pmayd** [comment]
Ah thanks yes I saw no update from you on this and so I decided for tomorrow to quickly do it myself with a materialized view so we can start working on the reports. You can have a look at the view I created in our test account and tell me if you had done it the same way. I tried to get it work with a temp table so I could drop the duplicated columns but it was not possible because of the id column so ended up with selecting every column

**Comment by pmayd** [comment]
You are great, thanks! I will update the query then
