### ISSUE TITLE
Product data categories

### ISSUE THREAD

**Issue by KonradUdoHannes** [CorrelAidSwitzerland/a4d#91]

**Comment by KonradUdoHannes** [comment]
@pmayd @tvolegtv Can you provide a few details on this issue in particular

- What is the path to the target file for reproduction the the bucket
- Was there a specific problem with the implementation or is it simply not done yet.

Feel free to point out other points that are important to mention, but once I'm certain I have the correct file paths I can probably start and then discuss any follow up questions along the way.

**Comment by pmayd** [comment]
Sorry I don't understand the first question, which bucket do you mean or need? You mean where the report can be found? I will paste you the link later and also more details that I have

**Comment by pmayd** [comment]
The bucket is `a4d-315220-documents`, the folder `from_tyla` and the file is called [CSP IMPACT_Numbers.xlsx](https://storage.cloud.google.com/a4d-315220-documents/from_tyla/CSP%20IMPACT_Numbers.xlsx). 

As you can see, the sheets are sorted by product category, so every product that falls into the insulin category should be collected under Insulin Impact, etc. 

And the whole approach here is that they gather the number of patients and from that calculate an estimate about the distributed products. I think we can omit this approach and work with the real figures directly.

Of course we need a good quality assessment in the end and compare our numbers with A4D's numbers so we can see how big the difference between the two approaches is.

Do you need anything else?

**Comment by pmayd** [comment]
Ah thanks yes this is also needed

**Comment by KonradUdoHannes** [comment]
Thanks guys. And no worries about answering a little bit later. I probably won't start coding before tomorrow, but I already wanted to start gathering relevant information upfront.

**Comment by tvolegtv** [comment]
@KonradUdoHannes List of products + product categories:
The list of products we use to report_unknown_products (R\read_product_data.R, reading_product_data_step2). 
You can find this list in the a4d_work\master_tracker_variables.xlsx (Stock_Summary).
This list is not complete, and we may need to add more unknown products from the historical data when we encounter errors in the logs. I have stored the product list in the xlsx file. I think it is good to have the product and group information in one place. If you prefer a different file format (not xlsx), please let me know and I will modify the read_product_data.R (load_stock_products) accordingly.
The group information should be in the "product_category" column, which is currently missing from steps 1 and 2. The create_table_product_data.R (preparing_product_fields function) adds this column and other 3 missing columns in step 3 and reorders all columns according to the schema. This means you can add the "product_category" column on step run_script_2_clean_data.R and the final schema should be correct.
